site_name: 'Backstage Test Docs'
site_description: 'Documentation for backstage-test service'

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api.md

plugins:
  - techdocs-core
